import { Metadata } from 'next';
import React from 'react';
import { notFound } from 'next/navigation';

// RSC

export const metadata: Metadata = {
    title: {
        absolute:"ProductId",
    },
    description: "Generated by create next app",
};

export default function ProductId({params}: {params: {productId: string}}) {

    //notFound() can only be used in RSC
    if (parseInt(params.productId) > 3) {
        notFound();
    };

    return (
        <div>
            <h1>Product id</h1>
        </div>
    );
};
