import { Metadata } from 'next';
import React from 'react';

// RSC

export const metadata: Metadata = {
    title: {
        absolute:"Products",
    },
    description: "Generated by create next app",
};

export default function Products() {

    return (
        <div>
            <h1>Products</h1>
        </div>
    )
};
